### ISSUE TITLE
The parameter `conjur_ssl_certificate` requires cert as a string, not a file.

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/ansible-conjur-host-identity#4]
When using the role, I got tripped up trying to pass a file path to a cert rather than the contents of the cert.  I was able to resolve this issue with the following:
```yml
- role: cyberark.conjur-host-identity
  ...
  conjur_ssl_certificate: "{{ lookup('file', '/src/certs/ca.crt') }}"
  ...
```
I also ran into an issue where I initially uploaded the Conjur Master CRT file rather than the CA CRT.  This results in a connection error when `conjur_validate_certs=True`.

I'd like to propose a few a couple of changes:
* Rename `conjur_ssl_certificate` to `conjur_ca_certificate`
* Add `conjur_ca_certificate_path`, which takes a path to the CA certificate.
